# Generated by Django 4.1.7 on 2023-02-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='date create')),
                ('updated_at', models.DateTimeField(verbose_name='date update')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='date create')),
                ('updated_at', models.DateTimeField(verbose_name='date update')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='date create')),
                ('updated_at', models.DateTimeField(verbose_name='date update')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.person')),
            ],
        ),
    ]
